#!/bin/bash
set -x
#
az vm create \
 --resource-group Test \
 --name Web \
 --image UbuntuLTS \
 --vnet-name AppNet \
 --subnet AppSubnet --nsg "" --asgs Web-ASG \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub \
 --public-ip-address Public_Web
#
az vm create \
 --resource-group Test \
 --name DB \
 --image UbuntuLTS \
 --vnet-name AppNet \
 --subnet DBNet --nsg "" --asgs DB-ASG \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub \
 --public-ip-address "" 
