#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Create VM A with default settings in resource group $RG"
#
set -x
az vm create \
 --resource-group $RG \
 --name A \
 --image UbuntuLTS \
 --admin-username azure \
 --generate-ssh-keys \
 --public-ip-address A_Public \
 --public-ip-address-allocation static
