#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Apply route-table Private to DBNet in resource group $RG"
#
set -x
#
# Apply route table
#
az network vnet subnet update \
  --resource-group $RG \
  --vnet-name AppNet --name DBNet \
  --route-table Private
