#!/bin/bash
set -x
#
# Apply NSG to subnets
#
az network vnet subnet update \
  --resource-group Test --vnet-name AppNet --name DBNet \
  --network-security-group "DB-NSG"
#
az network vnet subnet update \
  --resource-group Test --vnet-name AppNet --name AppSubnet \
  --network-security-group "Web-NSG"
