#!/bin/bash
#
# Create network security group
#
az network nsg create \
  --resource-group Test \
  --name Web
#
az network nsg create \
  --resource-group Test \
  --name DB
#
az network nsg rule create \
--resource-group Test \
--nsg-name Web \
--name Allow-Web-All \
--access Allow \
--protocol Tcp \
--direction Inbound \
--priority 100 \
--source-address-prefix Internet \
--source-port-range "*" \
--destination-address-prefix "172.16.1.0/24" \
--destination-port-range 80 443

