#!/bin/bash
set -x
#
# Create network security group
#
az network nsg create \
  --resource-group Test \
  --name DB-NSG
#
az network nsg rule create \
  --resource-group Test --nsg-name DB-NSG \
  --name Allow-DB-In --priority 100 \
  --access Allow --protocol Tcp --direction Inbound \
  --source-address-prefix "172.16.1.0/24" --source-port-range "*" \
  --destination-address-prefix "172.16.2.0/24" --destination-port-range 3306
#
az network nsg rule create \
  --resource-group Test --nsg-name DB-NSG \
  --name Allow-SSH-In --priority 110 \
  --access Allow --protocol Tcp --direction Inbound \
  --source-address-prefix "0.0.0.0/0" --source-port-range "*" \
  --destination-address-prefix "172.16.2.0/24" --destination-port-range 22
