#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Fix DB NSG in resource group $RG"
set -x
#
az network nsg rule create \
  --resource-group $RG --nsg-name DB-NSG \
  --name Deny-Vnet --priority 4000 \
  --access Deny --protocol Tcp --direction Inbound \
  --source-address-prefix VirtualNetwork --source-port-range "*" \
  --destination-address-prefix VirtualNetwork --destination-port-range "*"
